// Country codes for TMDB API filtering
export const countries = [
    // Major Markets
    { code: 'US', name: 'United States', flag: '🇺🇸' },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
    { code: 'CA', name: 'Canada', flag: '🇨🇦' },
    { code: 'AU', name: 'Australia', flag: '🇦🇺' },
    { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
    
    // Europe
    { code: 'DE', name: 'Germany', flag: '🇩🇪' },
    { code: 'FR', name: 'France', flag: '🇫🇷' },
    { code: 'IT', name: 'Italy', flag: '🇮🇹' },
    { code: 'ES', name: 'Spain', flag: '🇪🇸' },
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
    { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
    { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
    { code: 'AT', name: 'Austria', flag: '🇦🇹' },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
    { code: 'NO', name: 'Norway', flag: '🇳🇴' },
    { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
    { code: 'FI', name: 'Finland', flag: '🇫🇮' },
    { code: 'PL', name: 'Poland', flag: '🇵🇱' },
    { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
    { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
    { code: 'RO', name: 'Romania', flag: '🇷🇴' },
    { code: 'GR', name: 'Greece', flag: '🇬🇷' },
    { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
    { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
    { code: 'IS', name: 'Iceland', flag: '🇮🇸' },
    { code: 'RU', name: 'Russia', flag: '🇷🇺' },
    { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
    { code: 'TR', name: 'Turkey', flag: '🇹🇷' },
    { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
    { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
    { code: 'SK', name: 'Slovakia', flag: '🇸🇰' },
    { code: 'SI', name: 'Slovenia', flag: '🇸🇮' },
    { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
    { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
    { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
    
    // Asia
    { code: 'JP', name: 'Japan', flag: '🇯🇵' },
    { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
    { code: 'CN', name: 'China', flag: '🇨🇳' },
    { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
    { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
    { code: 'IN', name: 'India', flag: '🇮🇳' },
    { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
    { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
    { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
    { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
    { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
    { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
    { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
    { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
    { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
    { code: 'KH', name: 'Cambodia', flag: '🇰🇭' },
    { code: 'LA', name: 'Laos', flag: '🇱🇦' },
    { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
    { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
    { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
    
    // Middle East & North Africa
    { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
    { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
    { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
    { code: 'IL', name: 'Israel', flag: '🇮🇱' },
    { code: 'IQ', name: 'Iraq', flag: '🇮🇶' },
    { code: 'IR', name: 'Iran', flag: '🇮🇷' },
    { code: 'JO', name: 'Jordan', flag: '🇯🇴' },
    { code: 'LB', name: 'Lebanon', flag: '🇱🇧' },
    { code: 'SY', name: 'Syria', flag: '🇸🇾' },
    { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
    { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
    { code: 'MA', name: 'Morocco', flag: '🇲🇦' },
    { code: 'TN', name: 'Tunisia', flag: '🇹🇳' },
    { code: 'LY', name: 'Libya', flag: '🇱🇾' },
    
    // Latin America
    { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
    { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
    { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
    { code: 'CL', name: 'Chile', flag: '🇨🇱' },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
    { code: 'PE', name: 'Peru', flag: '🇵🇪' },
    { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
    { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
    { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
    { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
    { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
    { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
    { code: 'PA', name: 'Panama', flag: '🇵🇦' },
    { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
    { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
    { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
    { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
    { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
    { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
    
    // Africa
    { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
    { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
    { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
    { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
    { code: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
    { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
    { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
    { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' },
    { code: 'AO', name: 'Angola', flag: '🇦🇴' },
    { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
    { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
    { code: 'CM', name: 'Cameroon', flag: '🇨🇲' },
    { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮' },
    { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
    { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
    
    // Oceania
    { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
    { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬' },
];

export const getCountryByCode = (code) => {
    return countries.find(c => c.code === code);
};

